package com.example.eng_tr_quiz;


public class Adjective_Database {

    String[] english={

            "Different",
            "Used",
            "Important",
            "Every",
            "Large",
            "Available",
            "Popular",
            "Able",
            "Basic",
            "Known",
            "Various",
            "Difficult",
            "Several",
            "United",
            "Historical",
            "Hot",
            "Useful",
            "Mental",
            "Scared",
            "Additional",
            "Emotional",
            "Old",
            "Political",
            "Similar",
            "Healthy",
            "Financial",
            "Medical",
            "Traditional",
            "Federal",
            "Entire",
            "Strong",
            "Actual",
            "Significant",
            "Successful",
            "Electrical",
            "Expensive",
            "Pregnant",
            "Intelligent",
            "Interesting",
            "Poor",
            "Happy",
            "Responsible",
            "Cute",
            "Helpful",
            "Recent",
            "Willing",
            "Nice",
            "Wonderful",
            "Impossible",
            "Serious",
            "Huge",
            "Rare",
            "Technical",
            "Typical",
            "Competitive",
            "Critical",
            "Electronic",
            "Immediate",
            "Aware",
            "Educational",
            "Environmental",
            "Global",
            "Legal",
            "Relevant",
            "Accurate",
            "Capable",
            "Dangerous",
            "Dramatic",
            "Efficient",
            "Powerful",
            "Foreign",
            "Hungry",
            "Practical",
            "Psychological",
            "Severe",
            "Suitable",
            "Numerous",
            "Sufficient",
            "Unusual",
            "Consistent",
            "O",
            "Existing",
            "Famous",
            "Pure",
            "Afraid",
            "Obvious",
            "Careful",
            "Latter",
            "Unhappy",
            "Acceptable",
            "Aggressive",
            "Boring",
            "Distinct",
            "Eastern",
            "Logical",
            "Reasonable",
            "Strict",
            "Administrative",
            "Automatic",
            "Civil",
            "Former",
            "Massive",
            "Southern",
            "Unfair",
            "Visible",
            "Alive",
            "Angry",
            "Desperate",
            "Exciting",
            "Friendly",
            "Lucky",
            "Realistic",
            "Sorry",
            "Ugly",
            "Unlikely",
            "Anxious",
            "Comprehensive",
            "Curious",
            "Impressive",
            "Informal",
            "Inner",
            "Pleasant",
            "Sudden",
            "Terrible",
            "Unable",
            "Weak",
            "Wooden",
            "Asleep",
            "Confident",
            "Conscious",
            "Decent",
            "Embarrassed",
            "Guilty",
            "Lonely",
            "Mad",
            "Nervous",
            "Odd",
            "Remarkable",
            "Suspicious",
            "Tall",
            "Tiny",
            "More",
            "Some",
            "One",
            "All",
            "Many",
            "Most",
            "Other",
            "Even",
            "New",
            "Just",
            "Good",
            "Any",
            "Each",
            "Much",
            "Own",
            "Great",
            "Another",
            "Same",
            "Few",
            "Free",
            "Right",
            "Still",
            "Best",
            "Public",
            "Human",
            "Both",
            "Local",
            "Sure",
            "Better",
            "General",
            "Specific",
            "Enough",
            "Long",
            "Small",
            "Less",
            "High",
            "Certain",
            "Little",
            "Common",
            "Next",
            "Simple",
            "Hard",
            "Past",
            "Big",
            "Possible",
            "Particular",
            "Real",
            "Major",
            "Personal",
            "Current",
            "Left",
            "National",
            "Least",
            "Natural",
            "Physical",
            "Short",
            "Last",
            "Single",
            "Individual",
            "Main",
            "Potential",
            "Professional",
            "International",
            "Lower",
            "Open",
            "Alternative",
            "Special",
            "Working",
            "True",
            "Whole",
            "Clear",
            "Dry",
            "Easy",
            "Cold",
            "Commercial",
            "Full",
            "Low",
            "Primary",
            "Worth",
            "Necessary",
            "Positive",
            "Present",
            "Close",
            "Creative",
            "Green",
            "Late",
            "Fit",
            "Glad",
            "Proper",
            "Complex",
            "Content",
            "Due",
            "Effective",
            "Middle",
            "Regular",
            "Fast",
            "Independent",
            "Original",
            "Wide",
            "Beautiful",
            "Complete",
            "Active",
            "Negative",
            "Safe",
            "Visual",
            "Wrong",
            "Ago",
            "Quick",
            "Ready",
            "Straight",
            "White",
            "Direct",
            "Excellent",
            "Extra",
            "Pretty",
            "Unique",
            "Classic",
            "Final",
            "Overall",
            "Private",
            "Separate",
            "Estern",
            "Alone",
            "Familiar",
            "Official",
            "Perfect",
            "Bright",
            "Broad",
            "Comfortable",
            "Flat",
            "Rich",
            "Warm",
            "Young",
            "Heavy",
            "Valuable",
            "Correct",
            "Leading",
            "Slow",
            "Clean",
            "Fresh",
            "Normal",
            "Secret",
            "Tough",
            "Brown",
            "Cheap",
            "Deep",
            "Objective",
            "Secure",
            "Thin",
            "Chemical",
            "Cool",
            "Extreme",
            "Exact",
            "Fair",
            "Fine",
            "Formal",
            "Opposite",
            "Remote",
            "Total",
            "Vast",
            "Lost",
            "Smooth",
            "Dark",
            "Double",
            "Equal",
            "Firm",
            "Frequent",
            "Internal",
            "Sensitive",
            "Constant",
            "Minor",
            "Previous",
            "Raw",
            "Soft",
            "Solid",
            "Weird",
            "Amazing",
            "Annual",
            "Busy",
            "Dead",
            "False",
            "Round",
            "Sharp",
            "Thick",
            "Wise",
            "Equivalent",
            "Initial",
            "Narrow",
            "Nearby",
            "Proud",
            "Spiritual",
            "Wild",
            "Adult",
            "Apart",
            "Brief",
            "Crazy",
            "Prior",
            "Rough",
            "Sad",
            "Sick",
            "Strange",
            "External",
            "Illegal",
            "Loud",
            "Mobile",
            "Ordinary",
            "Royal",
            "Super",
            "Tight",
            "Upper",
            "Yellow",
            "Dependent",
            "Funny",
            "Gross",
            "Ill",
            "Spare",
            "Sweet",
            "Upstairs",
            "Usual",
            "Brave",
            "Calm",
            "Dirty",
            "Grand",
            "Honest",
            "Loose",
            "Male",
            "Quiet",
            "Brilliant",
            "Dear",
            "Drunk",
            "Empty",
            "Female",
            "Inevitable",
            "Neat",
            "Representative",
            "Silly",
            "Slight",
            "Smart",
            "Stupid",
            "Temporary",
            "Weekly",
            "That",
            "This",
            "What",
            "Which",
            "Time",
            "These",
            "Work",
            "No",
            "Only",
            "Then",
            "First",
            "Money",
            "Over",
            "His",
            "After",
            "Life",
            "Day",
            "Home",
            "Economic",
            "Away",
            "Fat",
            "Key",
            "Top",
            "Level",
            "Far",
            "Kind",
            "Live",
            "North",
            "Front",
            "Living",
            "Plus",
            "Maximum",
            "Red",
            "Ideal",
            "Minimum",
            "South",
            "Patient",
            "West",
            "Native",
            "Leather" };










    String[] turkish={
            "Farklı",
            "Kullanılmış",
            "Önemli",
            "Her",
            "Geniş",
            "Müsait, geçerli",
            "Popüler",
            "Becerikli",
            "Basit, temel",
            "Bilinen",
            "Türlü",
            "Zor",
            "Birkaç",
            "Birleşik",
            "Tarihi",
            "Sıcak",
            "Kullanışlı",
            "Zihinsel",
            "Korkmuş",
            "Ek, fazladan",
            "Duygusal",
            "Yaşlı, eski",
            "Siyasi, politik",
            "Benzer",
            "Sağlıklı",
            "Parasal",
            "Tıbbi",
            "Geleneksel",
            "Eyaletle ilgili; federal",
            "Tüm, hep",
            "Güçlü",
            "Güncel; gerçek",
            "Dikkate değer",
            "Başarılı",
            "Elektrikle ilgili",
            "Pahalı",
            "Hamile",
            "Zeki",
            "İlginç",
            "Yoksul",
            "Mutlu",
            "Sorumlu",
            "Sevimli",
            "Yardımsever",
            "Yeni olan; son",
            "İstekli",
            "Hoş",
            "Mükemmel",
            "İmkansız",
            "Ciddi",
            "Kocaman",
            "Nadir",

            "Teknik",
            "Özgün,tipik",
            "Rekabetçi",
            "Kritik",
            "Elektronik",
            "Yakın, hemen",
            "Farkında",
            "Eğitimsel",
            "Çevresel",
            "Küresel",
            "Yasal",
            "İlgili",
            "Kesin, tam",
            "Yetenekli",
            "Tehlikeli",
            "Dramatik",
            "Verimli",
            "Kuvvetli",
            "Yabancı",
            "Aç",
            "Pratik",
            "Psikolojik",
            "Şiddetli, ağır",
            "Uygun",
            "Çok sayıda",
            "Yeterli",
            "Sıradışı",
            "Tutarlı",
            "Kültürel",
            "Var olan, mevcut",
            "Ünlü",
            "Saf",
            "Ürkmüş",
            "Belli",
            "Dikkatli; bakımlı",
            "Sonraki",
            "Mutsuz",
            "Kabul edilebilir",
            "Saldırgan",
            "Sıkıcı",
            "Ayrı",
            "Doğu",
            "Mantıklı",
            "Akla yatkın",
            "Sıkı",
            "Yönetimsel",
            "Otomatik",
            "Sivil",
            "Önceki",
            "Tek parça, som",
            "Güney",
            "Adaletsiz",
            "Görünür",
            "Canlı",
            "Kızgın",
            "Çaresiz",
            "Heyecan verici",
            "Arkadaş canlısı",
            "Şanslı",
            "Gerçekçi",
            "Üzgün",
            "Çirkin",
            "Olası olmayan",
            "Kaygılı",
            "Kavrayışlı",
            "Meraklı",
            "Etkileyici",
            "Resmi olmayan",
            "İç, içsel",
            "Hoşnut",
            "Ani, birden",
            "Korkunç",
            "Yapamaz durumda",
            "Zayıf",
            "Tahta, ahşap",
            "Uykulu",
            "Kendi güvenen",
            "Bilinçli",
            "Terbiyeli",
            "Utangaç",
            "Suçlu",
            "Yalnız",
            "Çılgın",
            "Sinirli",
            "Garip; tek",
            "Kayda değer",
            "Şüpheli",
            "Uzun (boy)",
            "Mini",
            "Daha",
            "Biraz",
            "Bir",
            "Hepsi",
            "Çok",
            "En",
            "Diğer",
            "Çift",
            "Yeni",
            "Sadece",
            "İyi",
            "Herhangi",
            "Her bir",
            "Çok miktarda",
            "Öz, kendinin",
            "Muazzam",
            "Bir diğer",
            "Aynı",
            "Az",
            "Ücretsiz; serbest",
            "Doğru; sağ",
            "Sakin, durgun",
            "En iyi",
            "Kamusal",
            "İnsan; insani",
            "İkisi",
            "Yerel",
            "Emin",
            "Daha iyi",
            "Genel",
            "Özel; özgül",
            "Yeterli",
            "Uzun",
            "Küçük",
            "Daha az",
            "Yüksek",
            "Belirli",
            "Küçük, ufak",
            "Ortak; yaygın",
            "Sıradaki",
            "Basit ",
            "Zor",
            "Geçmiş",
            "Büyük",
            "Mümkün",
            "Özgü",
            "Gerçek",
            "Başlıca",
            "Kişisel",
            "Şu anki",
            "Sol",
            "Ulusal",
            "En az",
            "Doğal",
            "Fiziksel",
            "Kısa",
            "En son",
            "Tek; bekâr",
            "Bireysel",
            "Ana, esas",
            "Potansiyel",
            "Profesyonel",
            "Uluslararası",
            "Daha aşağı",
            "Açık",
            "Alternatif",
            "Özel",
            "Çalışan",
            "Doğru ",
            "Bütün",
            "Anlaşılır; temiz",
            "Kuru",
            "Kolay",
            "Soğuk",
            "Ticari",
            "Dolu",
            "Aşağı",
            "Birincil",
            "Değer",
            "Gerekli",
            "Olumlu",
            "Mevcut",
            "Yakın",
            "Yaratıcı",
            "Yeşil",
            "Geç",
            "Uygun",
            "Memnun",
            "Tam; doğru",
            "Karmaşık",
            "Razı",
            "Gereken; vakti dolmuş",
            "Etkili",
            "Orta",
            "Düzenli",
            "Hızlı",
            "Bağımsız",
            "Orijinal",
            "Geniş",
            "Güzel",
            "Eksiksiz",
            "Etkin",
            "Olumsuz",
            "Güvenli",
            "Görsel",
            "Yanlış",
            "Önce",
            "Çabuk",
            "Hazır",
            "Düz ",
            "Beyaz",
            "Doğrudan",
            "Kusursuz",
            "Fazladan",
            "Güzel; çok",
            "Benzersiz",
            "Klasik",
            "Son",
            "Ortalama",
            "Özel",
            "Ayrı",
            "Batı",
            "Yalnız",
            "Aşina, tanıdık",
            "Resmi",
            "Mükemmel",
            "Parlak",
            "Enli, geniş",
            "Rahat",
            "Düz",
            "Zengin",
            "Ilık",
            "Genç",
            "Ağır",
            "Değerli",
            "Doğru ",
            "İleri gelen",
            "Yavaş",
            "Temiz",
            "Taze",
            "Normal",
            "Gizli",
            "Zor",
            "Kahverengi",
            "Ucuz",
            "Derin",
            "Nesnel, tarafsız",
            "Güvenli",
            "İnce",
            "Kimyasal",
            "Soğukkanlı",
            "Aşırı, uç",
            "Tam, birebir",
            "Adil",
            "Güzel; iyi",
            "Resmi",
            "Karşıt, ters",
            "Uzak",
            "Toplam",
            "Uçsuz bucaksız",
            "Kayıp",
            "Pürüzsüz",
            "Karanlık",
            "Çift",
            "Eşit",
            "Sıkı",
            "Sık",
            "İçsel",
            "Hassas",
            "Sabit; sürekli",
            "Küçük",
            "Önceki",
            "Ham",
            "Yumuşak",
            "Katı",
            "Garip",
            "Şaşırtıcı",
            "Yıllık",
            "Meşgul",
            "Ölü",
            "Yanlış ",
            "Yuvarlak",
            "Keskin",
            "Kalın",
            "Bilge",
            "Eşdeğer",
            "İlk; baştaki",
            "Dar",
            "Yakında",
            "Gururlu",
            "Ruhsal",
            "Vahşi",
            "Yetişkin",
            "Ayrı",
            "Kısa",
            "Çılgın",
            "Öncelikli",
            "Kaba",
            "Üzgün",
            "Hasta",
            "Tuhaf",
            "Dışsal",
            "Yasadışı",
            "Gürültülü",
            "Hareketli, seyyar",
            "Sıradan",
            "Kraliyetle ilgili",
            "Süper",
            "Sıkı",
            "Üstteki",
            "Sarı",
            "Bağımlı",
            "Eğlenceli",
            "Brüt",
            "Hasta",
            "Yedek; fazla",
            "Tatlı",
            "Yukarıda; aklen",
            "Sıradan",
            "Cesur",
            "Sakin",
            "Kirli",
            "Büyük",
            "Dürüst",
            "Gevşek",
            "Erkek",
            "Dingin",
            "Parlak",
            "Sevgili",
            "Sarhoş",
            "Boş",
            "Kadın",
            "Kaçınılmaz",
            "Tertipli",
            "Temsilci",
            "Şımarık",
            "Hafif",
            "Akıllı",
            "Aptal",
            "Geçici",
            "Haftalık",
            "O",
            "O",
            "Ne",
            "Hangi",
            "Zaman",
            "Bunlar",
            "İş",
            "Hayır",
            "Sadece",
            "Sonra",
            "İlk",
            "Para",
            "Üzeri",
            "Onun",
            "Sonra",
            "Yaşam",
            "Gün",
            "Ev",
            "Ekonomik",
            "Uzak",
            "Şişman",
            "Anahtar",
            "En üst",
            "Seviye",
            "Uzak",
            "Kibar",
            "Canlı",
            "Kuzey",
            "Ön",
            "Yaşayan",
            "Artı",
            "En fazla",
            "Kırmızı",
            "İdeal",
            "En az",
            "Güney",
            "Sabırlı",
            "Batı",
            "Yerli",
            "Derin"

    };
}





