package com.example.eng_tr_quiz;


public class Adverb_Database {

    String[] english={

            "Actively",
            "Admittedly",
            "Alarmedly",
            "Angrily",
            "Apparently",
            "Badly",
            "Beautifully",
            "Bravely",
            "Brightly",
            "Beneficially",
            "Busily",
            "Calmly",
            "Carefully",
            "Casually",
            "Certainly",
            "Cheaply",
            "Cheerfully",
            "Correctly",
            "Collectively",
            "Comfortably",
            "Considerably",
            "Clearly",
            "Cleverly",
            "Creatively",
            "Cowardly",
            "Curiously",
            "Daily",
            "Decisively",
            "Deeply",
            "Delightfully",
            "Differently",
            "Disractedly",
            "Eagerly",
            "Early",
            "Easily",
            "Eternally",
            "Evidently",
            "Exremely",
            "Fairly",
            "Fast",
            "Firstly",
            "Fortunately",
            "Furiously",
            "Generously",
            "Gently",
            "Gladly",
            "Well",
            "Happily",
            "Hard",
            "Hardly",
            "Heavily",
            "Honestly",
            "Hungrily",
            "Immediately",
            "Jealously",
            "Joyfully",
            "Justifiably",
            "Kindly",
            "Lately",
            "Lazily",
            "Lastly",
            "Loudly",
            "Massively",
            "Naturally",
            "Nervously",
            "Nicely",
            "Noisily",
            "Openly",
            "Originally",
            "Painfully",
            "Patiently",
            "Perfectly",
            "Playfully",
            "Protectively",
            "Politely",
            "Quickly",
            "Quietly",
            "Reliably",
            "Sadly",
            "Safely",
            "Selfishly",
            "Separately",
            "Seriously",
            "Significantly",
            "Slowly",
            "Softly",
            "Suddenly",
            "Straight",
            "Strongly",
            "Stupidly",
            "Sweetly",
            "Successfully",
            "Terribly",
            "Tiredly",
            "Truly",
            "Viciously",
            "Widely",
            "Violently",
            "Wisely",
            "Wondefully",
            "Wrongly",

    };










    String[] turkish={
            "Aktif bir şekilde",
            "Hiç kuşkusuz",
            "Panikle",
            "Öfkeyle",
            "Görünüşe göre",
            "Fena halde",
            "Güzelce",
            "Cesurca",
            "Parlak bir şekilde",
            "Yararlı",
            "Meşgul bir şekilde",
            "Sakince",
            "Dikkatlice",
            "Tesadüfen",
            "Kesinlikle",
            "Ucuza",
            "Neşeyle",
            "Doğru şekilde",
            "Toplu olarak",
            "Rahatça",
            "Önemli ölçüde",
            "Açıkça",
            "Akıllıca",
            "Yaratıcı",
            "Korkakça",
            "Merakla",
            "Günden güne",
            "Kati surette",
            "Derinden",
            "Pek hoş",
            "Farklı olarak",
            "Dikkati dağılmış halde",
            "Hevesle",
            "Erkenden",
            "Kolayca",
            "Sonsuza dek",
            "Besbelli",
            "Aşırı derecede",
            "Dürüstçe",
            "Hızla",
            "İlk olarak",
            "Neyse ki",
            "Azgınca",
            "Bol bol",
            "Nazikçe",
            "Memnuniyetle",
            "İyi",
            "Mutlulukla",
            "Sert",
            "Zorlukla",
            "Ağır şekilde",
            "Dürüstçe",
            "İştahla",
            "Hemen",
            "Kıskançlıkla",
            "Sevinçle",
            "Halı olarak",
            "Nazikçe",
            "Son zamanlarda",
            "Tembelce",
            "Son olarak",
            "Gürültüyle",
            "Kitlesel",
            "Doğal olarak",
            "Sinirli olarak",
            "Güzelce",
            "Gürültüyle",
            "Açıkça",
            "Aslında",
            "Acıyla",
            "sabırla",
            "Kusursuzca",
            "Şakacı",
            "Korunmak",
            "Kibarca",
            "Hızlı bir şekilde",
            "Sessizce",
            "Güvenilir",
            "Üzüntülü bir şekilde",
            "Güvenli bir şekilde",
            "Bencilce",
            "Ayrı olarak",
            "Ciddi olarak",
            "Önemli ölçüde",
            "Yavaşça",
            "Yumuşakça",
            "Aniden",
            "Düzgünce",
            "Şiddetle",
            "Aptalca",
            "Tatlı bir şekilde",
            "Başarılı olarak",
            "Berbat bir şekilde",
            "Yorulmuş bir şekilde",
            "Gerçekten",
            "Şiddetle",
            "Geniş ölçüde",
            "Şiddetle",
            "Bilgece",
            "Olağanüstü bir şekilde",
            "Haksız yere",



    };
}





