package com.example.eng_tr_quiz;


public class Verb_Database {

    String[] english={

            "Accept",
            "Achieve",
            "Act ",
            "Add",
            "Admit",
            "Affect",
            "Afford ",
            "Agree",
            "Aim",
            "Allow",
            "Answer",
            "Appear ",
            "Apply",
            "Argue ",
            "Arrange",
            "Arrive",
            "Ask",
            "Attack",
            "Avoid",
            "Be",

            "Beat",
            "Become",
            "Begin",
           "Believe",
            "Bend",
            "Bet",
            "Bid",
            "Bite",
            "Bleed",
            "Blow",
            "Break",
            "Breed",
            "Bring",
            "Build",
            "Burn",
            "Burst",
            "Buy",
            "Call",
            "Catch",
            "Choose",
            "Come",
            "Cost",
            "Creep",
            "Cut",
            "Damage",
            "Dance",
            "Deal",
            "Decide",
            "Deliver",
            "Demand",
            "Deny",
            "Depend",
            "Describe",
            "Design ",
            "Destroy",
            "Develop",
            "Die",
            "Dig",
            "Do",
            "Draw",
            "Dream",
            "Drink",
            "Drive",
            "Eat",
            "End",
            "Enjoy",
            "Examine",
            "Exist",
            "Expect",
            "Experience",
            "Explain",
            "Express",
            "fall",
            "Feed",
            "Feel",
            "Fight",
            "Find",
            "Fly",
            "Fold",
            "Follow",
            "Force",
            "Forbid",
            "Forget",
            "Forgive",
            "Freeze",
            "Get",
            "Give",
            "Go",
            "Grow",
            "Hang",
            "Have",
            "Hear",
            "Help",
            "Hide",
            "Hit",
            "Hold",
            "Hurt",
            "Keep",
            "Know",
            "Lay",
            "Lead",
            "Lean",
            "Leave",
            "Lend",
            "Let",
            "Lie",
            "Like",
            "Live",
            "Look",
            "Lose",
            "Make",
            "Manage",
            "Mark",
            "Matter",
    "May",
    "Mean",
    "Meet",
    "Mention",
    "Mind",
    "Miss",
    "Move",
    "Need",
    "Notice",
    "Obtain",
    "Occur",
    "Offer",
    "Open",
    "Order",
    "Own",
    "Pass",
    "Pay",
    "Perform",
    "Pick",
    "Place",
    "Plan",
    "Play",
    "Put",
    "Quit",
   "Reach",
   "Read",
    "Realize",
    "Receive",
    "Recognize",
    "Record",
    "Reduce",
    "Reflect",
    "Refuse",
    "Regard",
    "Release",
    "Remain",
    "Remember",
    "Remove",
    "Repeat",
    "Replace",
    "Reply ",
    "Report ",
    "Represent",
    "Require",
    "Rest",
            "Return ",
    "Reveal",
    "Ring ",
    "Rise",
    "Roll",
    "Run",
    "Say",
    "See",
    "Seem",
    "Sell",
    "Send",
    "Set",
    "Settle",
    "Shake",
    "Shine",
    "Shoe",
    "Shoot",
    "Show",
    "Shrink",
    "Shut",
    "Sing",
    "Sink",
    "Sit",
    "Ski",
    "Slap",
    "Slay",
    "Slice",
    "Slide",
    "Slip",
    "Sleep",
    "Speak",
    "Spend",
    "Spill",
    "Spread",
    "Stand",
    "Start",
    "Steal",
    "Stick",
    "Sting",
    "Stink",
    "Swear",
    "Sweep",
    "Swim",
    "Swing",
    "Take",
    "Talk",
    "Teach",
    "Tear",
    "Tell",
    "Think",
            "Throw",
    "Touch",
    "Train",
    "Travel",
    "Treat",
     "Try",
    "Turn",
    "Understand",
    "Use",
    "Visit",
    "Vote",
    "Wait",
    "Walk",
    "Wake",
    "Want",
    "Warn",
    "Wear",
    "Win",
            "Wish",
            "Work",
            "Worry",
            "Write",



};










    String[] turkish={

            "Kabul etmek",
            "Elde etmek, başarmak",
            "Davranmak, hareket etmek",
            "Eklemek",
            "İtiraf etmek",
            "Etkilemek",
            "Satın almaya parası yetmek",
            "Aynı fikirde olmak",
            "Amaçlamak",
            "İzin vermek",
            "Cevap vermek",
            "Görünmek",
            "Uygulamak",
            "Tartışmak",
            "Ayarlamak, düzenlemek",
            "Varmak, ulaşmak",
            "Sormak, istemek",
            "Saldırmak",
            "Kaçınmak, önlemek",
            "Olmak",
            "Yenmek, vurmak",
            "Olmak, dönüşmek",
            "Başlamak",
            "İnanmak",
            "Eğilmek",
            "İddiaya girmek",
            "Teklif vermek",
            "Isırmak",
            "Kanamak",
            "Üflemek",
            "Kırılmak, (kurala) uymamak",
            "Üretmek, çoğaltmak",
            "Getirmek",
            "İnşa etmek, geliştirmek",
            "Yanmak, yakmak",
            "Patlamak, fırlamak",
            "Satın almak",
            "Aramak",
            "Yakalamak",
            "Seçmek",
            "Gelmek",
            "Mal olmak",
            "Ürkütmek",
            "Kesmek",
            "Zarar vermek",
            "Dans etmek",
            "Uğraşmak, çaresine bakmak",
            "Karar vermek",
            "Reslim etmek",
            "Talep etmek",
            "İnkar etmek",
            "Bağlı olmak, itimat etmek ",
            "Tanımlamak, tarif etmek",
            "Tasarlamak",
            "İmha etmek, yıkmak",
            "Geliştirmek",
            "Ölmek",
            "Kazımak",
            "Yapmak",
            "Çizmek",
            "Hayal,rüya görmek",
            "İçmek",
            "(Araç) sürmek",
            "Yemek",
            "Sona ermek, son vermek",
            "Zevk almak",
            "İncelemek, muayene etmek",
            "Var olmak",
            "Ümit etmek, beklemek",
            "Deneyim kazanmak",
            "Açıklamak, izah etmek",
            "İfade etmek, belli etmek",
            "Düşmek",
            "Beslemek",
            "Hissetmek",
            "Dövmek, dövüşmek",
            "Bulmak",
            "Uçmak",
            "Katlamak",
            "Takip etmek",
            "Zorlamak, güç kullanmak",
            "Yasaklamak",
            "Unutmak",
            "Affetmek",
            "Dondurmak, donmak",
            "Almak, elde etmek",
            "Vermek",
            "Gitmek",
            "Büyümek",
            "Asmak",
            "Sahip olmak",
            "Duymak",
            "Yardım etmek",
            "Saklanmak",
            "Çarpmak",
            "Tutmak, beklemek",
            "Acımak, acıtmak",
            "Tutmak, saklamak",
           "Bilmek",
            "Yatmak, uzanmak",
            "Yönetmek, liderlik etmek",
            "Eğilmek, dayanmak",
            "Terk etmek",
            "Borç vermek, ödünç vermek",
            "İzin vermek",
            "Yalan söylemek",
            "Beğenmek",
            "Yaşamak",
            "Bakmak",
            "Kaybetmek",
            "Yapmak",
            "Yönetmek, idare etmek",
            "İşaretlemek",
            "Önem taşımak, önemli olmak",
            "Mümkün kılmak, yapabilmek ",
            "Kastetmek, niyet etmek",
            "Buluşmak",
            "Bahsetmek",
            "Önemsemek, aldırmak",
            "Kaçırmak, özlemek",
            "Hareket etmek",
            "İhtiyaç duymak",
            "Fark etmek",
            "Edinmek, temin etmek",
            "Belirmek, vuku bulmak",
            "Teklif etmek",
            "Açmak",
            "Emir vermek",
            "Sahip olmak",
            "Pas geçmek, ihmal etmek",
            "Ödemek",
            "Sahnelemek",
            "Seçmek",
            "Yerleştirmek",
            "Plan yapmak",
            "Oynamak",
            "Koymak, yerleştirmek",
            "Bırakmak, vazgeçmek",
            "Erişmek, ulaşmak",
            "Okumak",
            "Farkına varmak, fark etmek",
            "Almak, teslim almak",
            "Tanımak",
            "Kaydetmek",
            "Miktarını azaltmak, düşürmek",
            "Yansıtmak",
            "Reddetmek, geri çevirmek",
            "Saymak",
            "Serbest bırakmak",
            "Arta kalmak",
            "Hatırlamak",
            "Kaldırmak, sökmek, gidermek",
            "Tekrarlamak",
            "Yer değiştirmek",
            "Cevap vermek",
            "İhbar etmek, bildirmek",
            "Temsil etmek",
            "Gerekmek, ihtiyacı olmak",
            "Dinlenmek, geri çekilmek",
            "Geri dönmek",
            "Ortaya çıkarmak",
            "(Telefon ya da zil) çalmak",
    "Doğmak, yükselmek",
    "Yuvarlamak",
    "Koşmak, işletmek",
    "Söylemek",
    "Görmek",
    "Görünmek",
    "Satmak",
    "Göndermek",
    "Ayarlamak, kurmak",
    "Razı olmak, yerleşmek",
    "Sallamak",
    "Parlamak",
    "Nallamak",
    "Vurmak, film çekmek",
    "Göstermek",
    "Küçülmek",
    "Kapatmak",
    "Şarkı söylemek",
    "Batmak",
    "Bturmak",
    "Kayak yapmak",
    "Tokatlamak",
    "Katletmek",
    "Doğramak",
    "Kaymak",
    "Kaydırmak, kayarak gitmek",
    "Uyumak",
    "Konuşmak",
    "Harcamak",
    "Tükürmek",
    "Yaymak",
    "Ayakta durmak",
    "Başlamak",
    "Çalmak, yürütmek",
    "Yapışmak",
    "Batmak, canını yakmak",
    "Kokuşmak",
    "Yemin etmek",
    "Süpürmek",
    "Yüzmek",
    "Sallanmak",
    "Almak",
    "Konuşmak",
    "Öğretmek",
    "Yırtmak",
    "Söylemek",
    "Düşünmek",
    "Fırlatmak",
    "Dokunmak",
    "Eğitmek",
    "Yolculuk yapmak, seyahat etmek",
    "Tedavi etmek, davranmak",
    "Denemek",
    "Dönmek",
    "Anlamak",
    "Kullanmak",
    "Ziyaret etmek",
    "Oy vermek",
    "Beklemek",
    "Yürümek",
    "Uyanmak",
    "İstemek",
    "Uyarmak",
    "Giymek",
    "Kazanmak",
    "Dilemek",
    "Çalışmak",
    "Endişelenmek",
    "Yazmak"

};
}





